apiVersion: v1
kind: Service
metadata:
  name: fastapi-server-service
spec:
  selector:
    app: fastapi-server
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: LoadBalancer  # Change to ClusterIP
